
# spring boot auto-configuracao
#  datasource
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-configure-datasource
# OracleDB connection settings
spring.datasource.url: jdbc:oracle:thin:@//10.0.120.51:1521/DBJRA
spring.datasource.username: gondola
spring.datasource.password: gondola
spring.datasource.driver-class-name: oracle.jdbc.OracleDriver

# HikariCP settings
#  spring.datasource.hikari.minimumIdle=5
#  spring.datasource.hikari.maximumPoolSize=20
#  spring.datasource.hikari.idleTimeout=30000
#  spring.datasource.hikari.maxLifetime=2000000
#  spring.datasource.hikari.connectionTimeout=30000
#  spring.datasource.hikari.poolName=HikariPoolBooks

# JPA settings
spring.jpa.database-platform: org.hibernate.dialect.Oracle10gDialect
spring.jpa.hibernate.use-new-id-generator-mappings: true
spring.jpa.hibernate.ddl-auto: update